### ISSUE TITLE
Some `thread_local!` can be replaced

### ISSUE THREAD

**Issue by eduardosm** [fabianschuiki/moore#152]
There are some `thread_local!` that seem to be used as a way of having a global constant whose expression needs to be evaluated at run-time.

For example: https://github.com/fabianschuiki/moore/blob/b3deaff234b01cced2b05c8cabc8d31ffecbae02/src/svlog/syntax/token.rs#L402-L406

However, this results on the value being initialized multiple times if used from different threads. An alternative would be to use the `sync::Lazy` type from the once_cell crate. The previous example would look like this:

```rust
use once_cell::sync::Lazy;
static TBL: Lazy<HashMap<String,Kw>> = Lazy::new(|| {
    let mut tbl = HashMap::new(); 
    $(tbl.insert($string.into(), Kw::$konst);)* 
    tbl
})
```

Thread local storage is no longer used, only one copy is used across threads and the value can be accessed directly (without the need of `.with()`). The main drawback is that it adds an extra dependency.

If you agree with this change, I can make a PR.

**Comment by fabianschuiki** [comment]
Yes you make a good point. I totally agree with this change. Feel free to open a PR :+1:
