### ISSUE TITLE
Cannot cast `reg` to `logic` with packed dimensions

### ISSUE THREAD

**Issue by thommythomaso** [fabianschuiki/moore#189]
```
module reg_logic_fail ( 
    input  wire [1:0] inp,
    output wire [1:0] oup 
);

    reg [1:0] internal;

    assign internal = inp;
    assign oup      = internal;

endmodule : reg_logic_fail

// but this works!

module reg_logic_pass ( 
    input  wire inp,
    output wire oup 
);

    reg internal;

    assign internal = inp;
    assign oup      = internal;

endmodule : reg_logic_fail

```

**Comment by fabianschuiki** [comment]
This seems to be an issue with how the compiler handles the casts. Technically the `reg` is an alias for `logic` in SV, but moore keeps it distinct for improved error reporting. But here the cast logic fails to implicitly transmute between them.

The fact that the problem only occurs in the presence of packed dimensions hints at different behaviour if the compiler casts to an intermediate SBVT or not.
